<a href="https://colab.research.google.com/github/minhtrong20130448/ML/blob/main/Lab_1_20130448_NguyenMinhTrong.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#Task 1.1
n = int(input('Nhap n: '));
print('n:', n)
list = []
for i in range(n):
    s = int(input('nhap phan tu: '))
    list.append(s)

print('Array is :',list)
print('Giá trị lớn nhất: ',max(list));
print('Giá trị nhỏ nhất: ',min(list));
print('Tổng: ', sum(list));

am = 0
duong = 0
for k in list:
  if k < 0:
    am = am + 1
  else:
    duong = duong + 1

print('số dương: ',duong)
print('số âm: ', am)

Nhap n: 1
n: 1
nhap phan tu: 2
Array is : [2]
Giá trị lớn nhất:  2
Giá trị nhỏ nhất:  2
Tổng:  2
số dương:  1
số âm:  0


In [ ]:
#Task 1.2
def Sn(n):
  if n == 0:
    return 1
  else:
    return Sn(n-1)+1/(2*n+1)

Sn(4)

In [2]:
#Task 1.3
from abc import ABC

class Product(ABC):
  def __init__(self, name, type, price, expiredDate):
    self.name = name
    self.type = type
    self.price = price
    self.expiredDate = expiredDate

  def getPrice(self):
    return self.price   
  
  def getType(self):
    return self.type

class ImportedProduct(Product):
  def __init__(self, name, type, price, expiredDate, fromCountry):
    self.name = name
    self.type = type
    self.price = price
    self.expiredDate = expiredDate
    self.fromCountry = fromCountry

class DomesticProduct(Product):
  def __init__(self, name, type, price, expiredDate):
    self.name = name
    self.type = type
    self.price = price
    self.expiredDate = expiredDate


class OrderItem(object):
  def __init__(self, item, amount):
    self.item = item
    self.amount = amount

  def getItem(self):
    return self.item

  def getAmount(self):
    return self.amount

class Order(object):
  def __init__(self, id, customer, employee, date, items):
    self.id = id
    self.customer = customer
    self.employee = employee
    self.date = date 
    self.items = items

  def getItems(self):
    return self.items
 
    
class OrderManager(object):
  def __init__(self, orders):
    self.orders = orders

  def highestPrice(self): 
    max = 0
    for order in self.orders:
      for item in order.getItems():
        value = item.getItem().getPrice()
        if max < value:
          max = value
    return max

  def statisticalProduct(self):
    dic = {}

    for order in self.orders:
      for item in order.getItems():
        value = item.getItem().getType()
        amount = item.getAmount()
        if value in dic:
          dic[value] = dic.get(value) + amount
        else :
          dic[value] = amount
          
    return dic


pro1 = ImportedProduct("product1", "type1", 10, "10-1-2022","Italya")
pro2 = ImportedProduct("product2", "type2", 50, "20-2-2022","Viet Nam")
pro3 = DomesticProduct("product3", "type1", 67, "10-2-2022")
pro4 = DomesticProduct("product4", "type2", 20, "20-6-2022")
pro5 = ImportedProduct("product5", "type4", 54, "11-1-2022", "Japan")
pro6 = DomesticProduct("product6", "type3", 40, "3-3-2022")

orderItem1 = OrderItem(pro1, 3);
orderItem2 = OrderItem(pro2, 1);
orderItem3 = OrderItem(pro4, 2);
orderItem4 = OrderItem(pro5, 4);
orderItem5 = OrderItem(pro6, 6);
orderItem6 = OrderItem(pro3, 1);

orders1 = []
orders1.append(orderItem1)
orders1.append(orderItem2)

orders2 = []
orders2.append(orderItem3)
orders2.append(orderItem4)

orders3 = []
orders3.append(orderItem5)
orders3.append(orderItem6)



order1 = Order("1", "Khạch Hang A", "Nhan Vien A", "10-1-2022", orders1)
order2 = Order("1", "Khạch Hang B", "Nhan Vien B", "22-2-2022", orders2)
order3 = Order("1", "Khạch Hang C", "Nhan Vien C", "20-4-2022", orders3)

orders = [] 
orders.append(order1)
orders.append(order2)
orders.append(order3)

manager = OrderManager(orders)

print(manager.highestPrice())
print(manager.statisticalProduct())




67
{'type1': 4, 'type2': 3, 'type4': 4, 'type3': 6}


In [9]:
#2.1
import numpy as np
x = np.arange(10,26,1)
reverseArr = np.flip(x)
reverseArr

array([25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15, 14, 13, 12, 11, 10])

In [20]:
#Task2.2
def repeatArray(array, time):
  arr = array
  for i in range(time-1):
    array = np.append(array,arr)
  return array

#test repeating 2 times
repeatArray([1,2,3,4], 2)

array([1, 2, 3, 4, 1, 2, 3, 4])

In [22]:
#Task2.3
def repleaceArray(array, numberReplace, numberGreater):
  array[array > numberGreater] = numberReplace
  return array

arr = np.array([[0.42, 0.48, 0.32], [0.74, 0.58, 0.38], [0.51, 0.34, 0.15]]).reshape(3,3)

repleaceArray(arr,0.5, 0.5)

array([[0.42, 0.48, 0.32],
       [0.5 , 0.5 , 0.38],
       [0.5 , 0.34, 0.15]])